### ISSUE TITLE
How to add support for SASS

### ISSUE THREAD

**Issue by tcchau** [LukeSheard/esbuild-scripts#163]
I'm receiving this error:
```
Error:[src/index.tsx] No loader is configured for ".scss" files: src/SCSS/bundle.scss
```

when building. How does one go about configuring the loader for SASS files?

**Comment by LukeSheard** [comment]
Hey @tcchau this should now be added in the latest release, It required a new plugin be added into esbuild equivalent to `sass-loader` for CSS. If you want to check it out and let me know if it works, I'm going to start working on adding some tests for this!
